### PR TITLE
Shared: Update `XCTFail` to `reportIssue`

### PR DESCRIPTION
**Pull request by stephencelis**
Another fix for a symbol mentioned in https://github.com/pointfreeco/swift-issue-reporting/issues/100

### CODE REVIEW

**Review by mbrandonw — APPROVED** [review]

**Comment by ryanmeisters** [comment]
is there a planned release for this one? 🙏🏼 😇

**Comment by mbrandonw** [comment]
Hi @ryanmeisters, this was already released as 1.12, but be sure to target 1.12.1 because we had a small fix right after the 1.12 release.

**Comment by ryanmeisters** [comment]
Oh I think Stephen added this after the 1.12.1 release in response to [this comment](https://github.com/pointfreeco/swift-issue-reporting/issues/100#issuecomment-2249001057), right?

**Comment by mbrandonw** [comment]
Oh sorry, no this specific commit has not yet been released yet. We can cut a 1.12.2 soon.

**Comment by stephencelis** [comment]
@ryanmeisters This PR should be mostly cosmetic, as issue reporting's `XCTFail` unconditionally reports issues to both XCTest _and_ Testing. Are you experiencing a particular issue?

**Comment by ryanmeisters** [comment]
Ah yeah I think this was the fix four our issue [here](https://github.com/pointfreeco/swift-issue-reporting/issues/100#issuecomment-2249005134).

Honestly not a huge deal if it's high effort to make a patch release. To solve it for us I temporarily pinned all the tca dependencies to the XCTestDyanmicOverlay versions. I was just trying to keep track of when I could undo that and get back to current versions.

**Comment by stephencelis** [comment]
Ah, sorry, I forgot about the symbol-related issue. We're planning a minor release with the new UIKit navigation tools this week, so when that's out it will get this patch. Thanks for your patience!

**Pull request merged**
