### PR TITLE
Add visionOS CI

### PR DESCRIPTION
**Pull request by stephencelis**
Should catch regressions in visionOS builds.

### CODE REVIEW

**Review by mbrandonw — APPROVED** [review]

**Comment by stephencelis** [comment]
That failure was expected. Just merged #2746 in to test the fix against this branch.

**Comment by peterbohac** [comment]
Thanks! Glad to see this CI pipeline added :)

**Comment by jshier** [comment]
This may also be an opportunity to try the new `macOS-14` builders (M1-based) for Xcode 15, for faster builds.

**Comment by stephencelis** [comment]
> This may also be an opportunity to try the new macOS-14 builders (M1-based) for Xcode 15, for faster builds.

Just saw that :smile: We'll give it a shot on another PR once this is merged.

**Comment by stephencelis** [comment]
@jshier Taking them for a test run on CasePaths and 15 minutes into a build still waiting for a runner to pick up the job: https://github.com/pointfreeco/swift-case-paths/actions/runs/7719232654/job/21042112183

Probably can't switch till they've been rolled out a bit more thoroughly.

**Comment by jshier** [comment]
> @jshier Taking them for a test run on CasePaths and 15 minutes into a build still waiting for a runner to pick up the job: https://github.com/pointfreeco/swift-case-paths/actions/runs/7719232654/job/21042112183
> 
> Probably can't switch till they've been rolled out a bit more thoroughly.

Too bad. Also, since they're macOS 14 images, you likely won't be able to run Xcode 14 builds anyway, so those can stay on the older runners.

(Wish GHA had availability graphs like other providers, just so we could see how backed up they are.)

**Comment by stephencelis** [comment]
@jshier Yeah seeing everything queued here, too. I wonder if this is just affecting the @pointfreeco org or if it's site wide?

**Comment by stephencelis** [comment]
> Too bad. Also, since they're macOS 14 images, you likely won't be able to run Xcode 14 builds anyway, so those can stay on the older runners.

Oh, and according to their runner images, macOS 14 does come installed with Xcode 14:

https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md

Was just waiting to see if it actually worked.

**Comment by jshier** [comment]
> Oh, and according to their runner images, macOS 14 does come installed with Xcode 14:
> 
> https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md

Odd, given Apple specifically blocks you from running Xcode 14 on macOS 14. I wonder if their docs are just out of date. Guess we'll see.

**Pull request merged**
