### PR TITLE
Fixed tree-based navigation: dismiss action is not sent when navigating back

### PR DESCRIPTION
**Pull request by tplaymeow**
Fixed https://github.com/pointfreeco/swift-composable-architecture/issues/2182.

Added `.id(id)` modifier to update value of `id` in `compactSend` closure when presenting a child feature.

### CODE REVIEW

**Comment by tplaymeow** [comment]
It seems to work for macOS, but breaks `navigationDestination` on iOS

**Comment by stephencelis** [comment]
@tplaymeow Can you explain more what didn't work in iOS?

Also, if it works in macOS but fails in iOS, could we conditionally compile the modifier? I think the following should work:

```swift
#if os(macOS)
  .id(id)
#endif
```

**Comment by tplaymeow** [comment]
@stephencelis 

It seems that this is SwiftUI bug. `navigationDestination(isPresented:)` does not update the Binding passed to the `isPresented` parameter when updating the view, although other methods for navigation (`popover(isPresented:)`, `sheet(isPresented:)`) do this. 

Because of this, when dismiss child feature, [`compacSend`](https://github.com/pointfreeco/swift-composable-architecture/blob/main/Sources/ComposableArchitecture/SwiftUI/PresentationModifier.swift#L223-L225
) contains an outdated `id` value and does not send `.dismiss` action.

I think we can not use `id` for `navigationDestination(isPresented:)` and just pass `Object Identifier(State.self)` instead of `$0.wrappedValue.map { _ in ObjectIdentifier(State.self) }`

This bug is also reproduced on some versions of iOS (16.0 - 16.3).
I have created a small project with a demonstration of this problem: [NavigationDestination.zip](https://github.com/pointfreeco/swift-composable-architecture/files/11886629/NavigationDestination.zip)

**Review by stephencelis — APPROVED** [review]
Looks good! Thanks for the detail deep dive into what was going wrong!

**Pull request merged**
