### PR TITLE
Convert all ActorIsolated to LockIsolated.

### PR DESCRIPTION
**Pull request by mbrandonw**

### CODE REVIEW

**Comment by Alex293** [comment]
Can you briefly explain the reason behind this ?

**Comment by mbrandonw** [comment]
> Can you briefly explain the reason behind this ?
> 
> will actorisolated be deprecated ?

Yeah, we will be deprecating `ActorIsolated` in swift-concurrency-extras. It really just has no advanced over `LockIsolated` (as far as we can tell), yet it's less ergonomic to use.

Do you have an example of where it is better to use `ActorIsolated` over `LockIsolated`?

**Comment by stephencelis** [comment]
@Alex293 For reference, here's the PR deprecating: https://github.com/pointfreeco/swift-concurrency-extras/pull/29

**Review by stephencelis — APPROVED** [review]

**Comment by Alex293** [comment]
I don’t have any specific use case, I was just wondering why, thanks !

**Pull request merged**
