### PR TITLE
ComposableCoreBluetooth

### PR DESCRIPTION
**Pull request by ph1ps**
This is a WIP pull request for the addition of CoreBluetooth into TCA as discussed in #248. 

- [ ] Add support for `CBPeripheralManager`
- [ ] Improve handling of immutability of `CBPeripheral`, `CBService`, ...
- [ ] Add documentation
- [ ] Add example usage
- [ ] Add unit tests

### CODE REVIEW

**Comment by mbrandonw** [comment]
Hey @ph1ps, this is really awesome, thanks for putting in the time!

We're actually going to start the process of extracting out these `CompsableABC` mini-libraries into their own repo for a few reasons:

1. Due to an SPM bug you can't actually depend on multiple of these libraries in a project. If you want `ComposableCoreLocation` and `ComposableCoreBluetooth` in your project you will run into "duplicate symbol" errors. However, if they were in their own repos you wouldn't have that problem.

2. We have seen a lot of people in the community interested in creating these libraries. So we'd like to find a way for people to introduce the libraries and maintain them outside the core library.

3. It's a little weird that we have to release all the libraries at once under the same tag, i.e. fixing something in `ComposableCoreMotion` forces us to make a release for `ComposableArchitecture`.

So, we are wondering if you would be interested in creating a `ph1ps/composable-core-bluetooth` repo on your user for this library. Later today we will be splitting off our core location and core motion libraries into their own repos under the pointfreeco org.

And then someday in the near future we plan on creating a "Composable Architecture Community" where we store all of these libraries. If you are willing, you could transfer your repo to that org and we could have one central place for all of these helper libraries.

What do you think?

**Comment by ph1ps** [comment]
@mbrandonw Sure I'm into that. I will create the repository and track my progress over there.

**Comment by mbrandonw** [comment]
Awesome, when it's ready to go let us know and we'll link to it from our readme.

**Comment by mluisbrown** [comment]
> We're actually going to start the process of extracting out these CompsableABC mini-libraries into their own repo for a few reasons:

This is great news, as that would help in the [ReactiveSwift port](https://github.com/trading-point/reactiveswift-composable-architecture) too, since I have to do an SPM hack to make *only* `ComposableArchitecture` available for Linux, and not the others 👍

**Comment by stephencelis** [comment]
@mluisbrown We've finished this extraction and released 0.9.0. Let us know if you have any issues or concerns!

**Pull request closed without merging**
