### PR TITLE
Add start and stop for heading

### PR DESCRIPTION
**Pull request by joeblau**
Add support for starting and stopping heading updates.

### CODE REVIEW

**Comment by mbrandonw** [comment]
Hey @joeblau, good catch on us not properly handling the start/stopUpdatingHeading! 

One thing to note is that we have already started a "composable Core Motion" branch here: https://github.com/pointfreeco/swift-composable-architecture/compare/ccm

I been meaning to put the final touches on it and ship it. What do you think about removing the Core Motion specific stuff from this branch and just leaving the Core Location update so that we can merge this, and then I'll whip up the core motion PR today/tomorrow so that we can release it next week?

**Comment by joeblau** [comment]
Oh nice! let me close this — I'm just doing updates for myself.

**Comment by mbrandonw** [comment]
FWIW I thought the changes on these lines were def worth keeping:

https://github.com/pointfreeco/swift-composable-architecture/pull/192/files#diff-81b1d12cc6443007e3c54b9b91a486e2R129-R139

That's a big oversight on our part right now.

**Comment by joeblau** [comment]
When you create the PR for merging that branch, can you tag me on it. After it's merged, I can go back in and plumb everything is a series of smaller PRs.

I'm actively making a ton of commits as I'm working on something :)

**Comment by mbrandonw** [comment]
👍 can do!

**Pull request closed without merging**
