### PR TITLE
Spanish Translation of TCA's README

### PR DESCRIPTION
**Pull request by pitt500**
Hi, I took the time to contribute to this wonderful project by creating a translation to Spanish. I think this will help a lot of people in LatAm and Spain to understand TCA in their language.

The README includes the latest concurrency updates made. Feel free to ask me any questions.

Regards,
Pitt

### CODE REVIEW

**Comment by acosmicflamingo** [comment]
Pretty nice! Should the title be "La Arquitectura Componible" or would that be too much?

**Comment by pitt500** [comment]
> Pretty nice! Should the title be "La Arquitectura Componible" or would that be too much?

Well, I followed the same approach like the others translations and kept the title in English.

TBH "La Arquitectura Componible" makes me feel really weird 😂

**Review by mbrandonw — APPROVED** [review]
Awesome, thanks so much @pitt500!

Glad you translated the newest readme for the 0.39.0 release. 😁 Sadly the other translations are now a lil out of date.

**Comment by pitt500** [comment]
You're welcome @mbrandonw, I'm glad to help 😄!

Special thanks to @astramex19 and @juan-pablo-rodriguez that helped me review the doc finding typos and misspellings 🙏🏻

**Pull request merged**
